ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecommerce/store/urls.py
from django.urls import path

from . import views
app_name = 'store'
urlpatterns = [
        #Leave as empty string for base url
	path('', views.store, name="store"),
	path('cart/', views.cart, name="cart"),
	path('checkout/', views.checkout, name="checkout"),
    path('productdetail/<slug:slug>/',views.productdetail,name="productdetail"),
    path('listcategory/<slug:category_slug>/',views.category_list,name="category_list"),
	path('update_item/',views.updateItem,name="update_item"),
    path('process_order/',views.processOrder,name="process_order"),
]

ecommerce/store/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.
class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True,blank=True)
    name = models.CharField(max_length=200,null=True)
    email = models.CharField(max_length=200,null=True)

    def __str__(self):
        return self.name

class Category(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('store:category_list', args=[self.slug])

class Product(models.Model):
        category = models.ForeignKey(Category, on_delete=models.CASCADE)
        name = models.CharField(max_length=200,null=True)
        slug = models.SlugField(unique=True,null=True)
        price = models.DecimalField(max_digits=9, decimal_places=0)
        image = models.ImageField(null=True, blank=True)
        digital = models.BooleanField(default=False, null=True, blank=False)

        def __str__(self):
            return self.name
        def get_absolute_url(self):
            return reverse('store:productdetail', args=[self.slug])
        @property
        def imageURL(self):
            try:
                url = self.image.url
            except:
                url = ''
            return url

class Order(models.Model):
    customer = models.ForeignKey(Customer,on_delete=models.SET_NULL,blank=True,null=True)
    date_orderd = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False,null = True,blank=False)
    transaction_id = models.CharField(max_length=200,null=True)
    def __str__(self):
        return str(self.id)

    @property
    def shipping(self):
        shipping = False
        orderitems = self.orderitem_set.all()
        for i in orderitems:
            if i.product.digital == False:
                shipping = True
        return shipping
    @property
    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total

    @property
    def get_cart_items(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.quantity for item in orderitems])
        return total


class OrderItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, blank=True, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, blank=True, null=True)
    quantity = models.IntegerField(default=0,null=True,blank = True)
    date_added = models.DateTimeField(auto_now_add=True)

    @property
    def get_total(self):
        total = self.product.price * self.quantity
        return total

class ShippingAddress(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, blank=True, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, blank=True, null=True)
    address = models.CharField(max_length=200,null=True)
    city = models.CharField(max_length=200, null=True)
    state = models.CharField(max_length=200, null=True)
    zipcode = models.CharField(max_length=200, null=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.address

ecommerce/store/views.py
from django.shortcuts import render, get_object_or_404
from django.http import JsonResponse
from .models import *
import json
import datetime
from .utils import cookieCart, cartData, guestOrder

# Create your views here.
def store(request):
    data = cartData(request)
    cartItems = data['cartItems']
    categorys = Category.objects.all()
    products = Product.objects.all()
    context = {'products':products, 'categorys': categorys, 'cartItems': cartItems}
    return render(request, 'store/store.html', context)

def productdetail(request,slug):
    categorys = Category.objects.all()
    product = get_object_or_404(Product,slug=slug)
    context = {'categorys': categorys, 'product':product}
    return render(request, 'store/productdetail.html', context)

def category_list(request, category_slug):
    data = cartData(request)
    cartItems = data['cartItems']
    categorys = Category.objects.all()
    category = get_object_or_404(Category, slug=category_slug)
    products = Product.objects.filter(category=category)
    context = {'category': category, 'products': products, 'categorys': categorys, 'cartItems': cartItems}
    return render(request, 'store/category.html', context)

def cart(request):
    data = cartData(request)
    cartItems = data['cartItems']
    order = data['order']
    items = data['items']

    categorys = Category.objects.all()
    context = {'categorys': categorys, 'items': items, 'order': order, 'cartItems': cartItems}
    return render(request, 'store/cart.html', context)


def checkout(request):
    data = cartData(request)
    cartItems = data['cartItems']
    order = data['order']
    items = data['items']

    categorys = Category.objects.all()
    context = {'categorys': categorys, 'items': items, 'order': order, 'cartItems': cartItems}
    return render(request, 'store/checkout.html', context)

def updateItem(request):
    data = json.loads(request.body)
    productId = data['productId']
    action = data['action']

    print('Action:', action)
    print('productId:', productId)

    customer = request.user.customer
    product = Product.objects.get(id=productId)
    order, created = Order.objects.get_or_create(customer=customer, complete=False)

    orderItem, created = OrderItem.objects.get_or_create(order=order, product=product)

    if action == 'add':
        orderItem.quantity = (orderItem.quantity +1)
    elif action == 'remove':
        orderItem.quantity = (orderItem.quantity -1)

    orderItem.save()

    if orderItem.quantity <= 0:
        orderItem.delete()
    return JsonResponse('Item was added', safe=False)

# from django.views.decorators.csrf import csrf_exempt
# @csrf_exempt
def processOrder(request):
    transaction_id = datetime.datetime.now().timestamp()
    data = json.loads(request.body)
    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, complete=False)

    else:
        customer, order = guestOrder(request, data)

    total = float(data['form']['total'])
    order.transaction_id = transaction_id

    if total == float(order.get_cart_total):
        order.complete = True
    order.save()
    if order.shipping == True:
        ShippingAddress.objects.create(
            customer=customer,
            order=order,
            address=data['shipping']['address'],
            city=data['shipping']['city'],
            state=data['shipping']['state'],
            zipcode=data['shipping']['zipcode'],
        )
    return JsonResponse('Payment complete!', safe=False)

ecommerce/store/templates/store/cart.html
{% extends 'store/main.html' %}
{% load static %}
{% block content %}
<div class="container" style="margin-top:50px">
	<div class="row">
		<div class="col-lg-12">
			<div class="box-element">
                 <a  class="btn btn-outline-dark" href="{% url 'store:store' %}">&#x2190; Quay lại</a>
				<br>
				<br>
				<table class="table">
					<tr>
						<th><h5>Số lượng: <strong>{{order.get_cart_items}}</strong></h5></th>
						<th><h5>Tổng tiền:<strong>{{order.get_cart_total}}</strong></h5></th>
						<th>
							<a  style="float:right; margin:5px;" class="btn btn-success" href="{% url 'store:checkout' %}">Thanh toán</a>
						</th>
					</tr>
				</table>
			</div>

			<br>
			<div class="box-element">
                <div class="cart-row">
					<div style="flex:2"></div>
					<div style="flex:2"><strong>Tên</strong></div>
					<div style="flex:1"><strong>Giá</strong></div>
					<div style="flex:1"><strong>Số lượng</strong></div>
					<div style="flex:1"><strong>Tổng tiền</strong></div>
				</div>
                {% for item in items %}
				<div class="cart-row">
					<div style="flex:2"><img class="row-image" src="{{item.product.imageURL}}"></div>
					<div style="flex:2"><p>{{item.product.name}}</p></div>
					<div style="flex:1"><p>{{item.product.price}}</p></div>
					<div style="flex:1">
						<p class="quantity">{{item.quantity}}</p>
						<div class="quantity">
							<img data-product={{item.product.id}} data-action="add" class="chg-quantity update-cart" src="{% static  'images/arrow-up.png' %}">

							<img data-product={{item.product.id}} data-action="remove" class="chg-quantity update-cart" src="{% static  'images/arrow-down.png' %}">
						</div>
					</div>
					<div style="flex:1"><p>{{item.get_total}}</p></div>
				</div>
				{% endfor %}
			</div>
		</div>
	</div>
</div>
{% endblock content %}

ecommerce/store/templates/store/category.html
{% extends 'store/main.html' %}
{% load static %}
{% block content %}

<div class="container" style="margin-top:50px">
<div class="container">
     <div class="row">
		 {% for product in products %}
		<div class="col-lg-3">
			<div class="product">
				<div class="product-img">
					<img src="{{product.imageURL}}" alt="">
					<div class="product-label">
						<span class="new">NEW</span>
					</div>
				</div>
				<div class="product-body">
					<p class="product-category">{{product.category}}</p>
					<h3 class="product-name"><a href="#">{{product.name}}</a></h3>
					<h4 class="product-price">{{product.price}} VNĐ</h4>
				</div>
				<div class="add-to-cart">
					<button data-product={{product.id}} data-action="add" class="add-to-cart-btn update-cart"><i class="fa fa-shopping-cart"></i> thêm vào giỏ hàng</button>
				</div>
                <div id="slick-nav-1" class="products-slick-nav"></div>
			</div>
		</div>
{% endfor %}
	</div>
</div>
</div>
{% endblock content %}

ecommerce/store/templates/store/checkout.html
{% extends 'store/main.html' %}
{% load static %}
{% block content %}

<div class="container" style="margin-top:50px">
     <div class="row">
		<div class="col-lg-6">
			<div class="box-element" id="form-wrapper">
				<form id="form">
					{%  csrf_token %}
					<div id="user-info">
						<div class="form-field">
							<input required class="form-control" type="text" name="name" placeholder="Name..">
						</div>
						<div class="form-field">
							<input required class="form-control" type="email" name="email" placeholder="Email..">
						</div>
					</div>

					<div id="shipping-info">
						<hr>
						<p>Thông tin địa chỉ:</p>
						<hr>
						<div class="form-field">
							<input class="form-control" type="text" name="address" placeholder="Address..">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="city" placeholder="Thành phố..">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="state" placeholder="Quận/huyện..">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="zipcode" placeholder="Mã code..">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="country" placeholder="Mã free ship..">
						</div>
					</div>

					<hr>
					<input id="form-button" class="btn btn-success btn-block" type="submit" value="Continue">
				</form>
			</div>
             <br>
			<div class="box-element hidden" id="payment-info">
				<small>Paypal</small>
				<button id="make-payment">Thực hiện thanh toán</button>
			</div>

		</div>

		<div class="col-lg-6">
            <div class="box-element">
				<a  class="btn btn-outline-dark" href="{% url 'store:cart' %}">&#x2190; Quay lại giỏ hàng</a>
				<hr>
				<h3>Đồ đã đặt</h3>
				<hr>
				{% for item in items %}
				<div class="cart-row">
					<div style="flex:2"><img class="row-image" src="{{item.product.imageURL}}"></div>
					<div style="flex:2"><p>{{item.product.name}}</p></div>
					<div style="flex:1"><p>{{item.product.price}}</p></div>
					<div style="flex:1"><p>x{{item.quantity}}</p></div>
				</div>
				{% endfor %}
				<h5>Số lượng:   {{order.get_cart_items}}</h5>
				<h5>Tổng tiền:   {{order.get_cart_total}}</h5>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
	var shipping = '{{order.shipping}}'
	var total = '{{order.get_cart_total}}'

	if(shipping == 'False'){
		document.getElementById('shipping-info').innerHTML =''
	}
	if(user != 'AnonymousUser'){
		document.getElementById('user-info').innerHTML =''
	}
	if(shipping == 'False' && user != 'AnonymousUser'){
		document.getElementById('form-wrapper').classList.add("hidden");
		document.getElementById('payment-info').classList.remove("hidden");
	}

    var form = document.getElementById('form')

	csrftoken = form.getElementsByTagName("input")[0].value
	console.log("Newtoken:",form.getElementsByTagName("input")[0].value)

	form.addEventListener('submit',function (e){
		e.preventDefault()
		console.log('Form submit ...')
		document.getElementById('form-button').classList.add('hidden')
		document.getElementById('payment-info').classList.remove('hidden')
	})

	document.getElementById('make-payment').addEventListener('click',function (e){
		submitFormData()
	})
	function submitFormData(){
		console.log('Payment button')

		var userFormData = {
			'name':null,
			'email':null,
			'total':total,
		}
		var shippingInfo = {
			'address':null,
			'city':null,
			'state':null,
			'zipcode':null,
		}
		if(shipping != 'False'){
			shippingInfo.address = form.address.value
			shippingInfo.city = form.city.value
			shippingInfo.state = form.state.value
			shippingInfo.zipcode = form.zipcode.value
		}
		if(user == 'AnonymousUser'){
			userFormData.name = form.name.value
			userFormData.email = form.email.value
		}
		var url = '/process_order/'
		fetch(url,{
			method:'POST',
			headers:{
				'Content-Type':'application/json',
				'X-CSRFToken':csrftoken,
			},
			body:JSON.stringify({'form':userFormData, 'shipping':shippingInfo})

		})
		.then((response)=> response.json())
		.then((data) =>{
              console.log('Success:',data);
			  alert('Giao dịch thành công');

			  cart = {}
			document.cookie = 'cart=' + JSON.stringify(cart) + ";domain=;path=/"
			  window.location.href="{% url 'store:store' %}"
         })
	}

</script>
{% endblock content %}

ecommerce/store/templates/store/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1" />
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
		 <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

		<title>Ecommerce </title>
          <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
 		<!-- Google font -->
 		<link href="https://fonts.googleapis.com/css?family=Montserrat:400,500,700" rel="stylesheet">

 		<!-- Bootstrap -->
 		<link type="text/css" rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>

 		<!-- Slick -->
 		<link type="text/css" rel="stylesheet" href="{% static 'css/slick.css' %}"/>
		<link type="text/css" rel="stylesheet" href="{% static 'css/slick-theme.css' %}"/>

 		<!-- nouislider -->
		<link type="text/css" rel="stylesheet" href="{% static 'css/nouislider.min.css' %}"/>

 		<!-- Font Awesome Icon -->
 		<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">

 		<!-- Custom stlylesheet -->
 	    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

		<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
		<!--[if lt IE 9]>
		  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
		  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->


		<script type="text/javascript">
			var user = '{{request.user}}'

			function getToken(name){
			var cookieValue = null;
			if(document.cookie && document.cookie !== ''){
			   var cookies = document.cookie.split(';');
			for (var i = 0;i< cookies.length;i++){
			var cookie = cookies[i].trim();
			if(cookie.substring(0,name.length +1)===(name +'=')){
			cookieValue = decodeURIComponent(cookie.substring(
			name.length +1));
			break;
			}
			}
			}
			return cookieValue;
			}
			var csrftoken = getToken('csrftoken');
			console.log('CSRFTOKEN',csrftoken)
			function getCookie(name){
				var cookieArr = document.cookie.split(";");
				for(var i = 0;i<cookieArr.length;i++){
					var cookiePair = cookieArr[i].split("=");
					if(name == cookiePair[0].trim()){
						return decodeURIComponent(cookiePair[1]);
					}
				}
				return null;
			}
            var cart = JSON.parse(getCookie('cart'))
			if(cart == undefined){
				cart={}
				console.log('cart was ')
				document.cookie = 'cart=' +JSON.stringify(cart)+";domain=;path=/"
			}
			console.log('cart:',cart)
		</script>
    </head>
	<body>
		<!-- HEADER -->
		<header>
			<!-- TOP HEADER -->

			<!-- /TOP HEADER -->

			<!-- MAIN HEADER -->
			<div id="header">
				<!-- container -->
				<div class="container">
					<!-- row -->
					<div class="row">
						<!-- LOGO -->
						<div class="col-md-3">
							<div class="header-logo">
								<a href="{% url 'store:store' %}" class="logo">
									<img src="{% static 'image/logo.png' %}" alt="">
								</a>
							</div>
						</div>
						<!-- /LOGO -->

						<!-- SEARCH BAR -->
						<div class="col-md-6">
							<div class="header-search">
								<form>
									<select class="input-select">
										<option value="0">All Categories</option>
										<option value="1">Category 01</option>
										<option value="1">Category 02</option>
									</select>
									<input class="input" placeholder="Search here">
									<button class="search-btn">Search</button>
								</form>
							</div>
						</div>
						<!-- /SEARCH BAR -->

						<!-- ACCOUNT -->
						<div class="col-md-2 clearfix">
							<div class="header-ctn">
								<!-- Wishlist -->
								<!-- /Wishlist -->

								<!-- Cart -->
								<div class="dropdown">
									<a href="{% url 'store:cart' %}">
    		                           <img  id="cart-icon" src="{% static 'image/cart.png' %}">
										<div class="qty">{{cartItems}}</div>
										<header>Giỏ hàng</header>
									</a>
								</div>
								<!-- /Cart -->

								<!-- Menu Toogle -->
								<!-- /Menu Toogle -->
							</div>
						</div>
						<!-- /ACCOUNT -->
					</div>
					<!-- row -->
				</div>
				<!-- container -->
			</div>
			<!-- /MAIN HEADER -->
		</header>
		<!-- /HEADER -->

		<!-- NAVIGATION -->
		<nav id="navigation" class="navbar-expand-sm">
			<!-- container -->
			<div class="container">
				<!-- responsive-nav -->
				<div id="responsive-nav">
					<!-- NAV -->
					<ul class="main-nav nav navbar-nav">
						<li class="active"><a href="{% url 'store:store' %}">Home</a></li>

						{% for category in categorys %}
						<li><a href="{{category.get_absolute_url}}">{{category.title}}</a></li>
						{% endfor %}
					</ul>
					<!-- /NAV -->
				</div>
				<!-- /responsive-nav -->
			</div>
			<!-- /container -->
		</nav>

		<!-- /NAVIGATION -->

		<!-- BREADCRUMB -->

		<!-- /BREADCRUMB -->

		<!-- SECTION -->
        <div class="container">
                {% block content %}


                 {% endblock content %}
		</div>
		<!-- /SECTION -->

		<!-- NEWSLETTER -->
		<div id="newsletter" class="section">
			<!-- container -->
			<div class="container">
				<!-- row -->
				<div class="row">
					<div class="col-md-12">
						<div class="newsletter">
							<p>Sign Up for the <strong>NEWSLETTER</strong></p>
							<form>
								<input class="input" type="email" placeholder="Enter Your Email">
								<button class="newsletter-btn"><i class="fa fa-envelope"></i> Subscribe</button>
							</form>
							<ul class="newsletter-follow">
								<li>
									<a href="#"><i class="fa fa-facebook"></i></a>
								</li>
								<li>
									<a href="#"><i class="fa fa-twitter"></i></a>
								</li>
								<li>
									<a href="#"><i class="fa fa-instagram"></i></a>
								</li>
								<li>
									<a href="#"><i class="fa fa-pinterest"></i></a>
								</li>
							</ul>
						</div>
					</div>
				</div>
				<!-- /row -->
			</div>
			<!-- /container -->
		</div>
		<!-- /NEWSLETTER -->

		<!-- FOOTER -->
		<footer id="footer">
			<!-- top footer -->
			<div class="section">
				<!-- container -->
				<div class="container">
					<!-- row -->
					<div class="row">
						<div class="col-md-3 col-xs-6">
							<div class="footer">
								<h3 class="footer-title">About Us</h3>
								<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut.</p>
								<ul class="footer-links">
									<li><a href="#"><i class="fa fa-map-marker"></i>1734 Stonecoal Road</a></li>
									<li><a href="#"><i class="fa fa-phone"></i>+021-95-51-84</a></li>
									<li><a href="#"><i class="fa fa-envelope-o"></i>email@email.com</a></li>
								</ul>
							</div>
						</div>

						<div class="col-md-3 col-xs-6">
							<div class="footer">
								<h3 class="footer-title">Categories</h3>
								<ul class="footer-links">
									<li><a href="#">Hot deals</a></li>
									<li><a href="#">Laptops</a></li>
									<li><a href="#">Smartphones</a></li>
									<li><a href="#">Cameras</a></li>
									<li><a href="#">Accessories</a></li>
								</ul>
							</div>
						</div>

						<div class="clearfix visible-xs"></div>

						<div class="col-md-3 col-xs-6">
							<div class="footer">
								<h3 class="footer-title">Information</h3>
								<ul class="footer-links">
									<li><a href="#">About Us</a></li>
									<li><a href="#">Contact Us</a></li>
									<li><a href="#">Privacy Policy</a></li>
									<li><a href="#">Orders and Returns</a></li>
									<li><a href="#">Terms & Conditions</a></li>
								</ul>
							</div>
						</div>

						<div class="col-md-3 col-xs-6">
							<div class="footer">
								<h3 class="footer-title">Service</h3>
								<ul class="footer-links">
									<li><a href="#">My Account</a></li>
									<li><a href="#">View Cart</a></li>
									<li><a href="#">Wishlist</a></li>
									<li><a href="#">Track My Order</a></li>
									<li><a href="#">Help</a></li>
								</ul>
							</div>
						</div>
					</div>
					<!-- /row -->
				</div>
				<!-- /container -->
			</div>
			<!-- /top footer -->

			<!-- bottom footer -->
			<div id="bottom-footer" class="section">
				<div class="container">
					<!-- row -->
					<div class="row">
						<div class="col-md-12 text-center">
							<ul class="footer-payments">
								<li><a href="#"><i class="fa fa-cc-visa"></i></a></li>
								<li><a href="#"><i class="fa fa-credit-card"></i></a></li>
								<li><a href="#"><i class="fa fa-cc-paypal"></i></a></li>
								<li><a href="#"><i class="fa fa-cc-mastercard"></i></a></li>
								<li><a href="#"><i class="fa fa-cc-discover"></i></a></li>
								<li><a href="#"><i class="fa fa-cc-amex"></i></a></li>
							</ul>
							<span class="copyright">
								<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
								Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
							<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
							</span>
						</div>
					</div>
						<!-- /row -->
				</div>
				<!-- /container -->
			</div>
			<!-- /bottom footer -->
		</footer>
		<!-- /FOOTER -->

		<!-- jQuery Plugins -->
		 <script src="{% static 'js/jquery.min.js' %}"></script>
		<script src="{% static 'js/bootstrap.min.js' %}"></script>
		<script src="{% static 'js/slick.min.js' %}"></script>
		<script src="{% static 'js/nouislider.min.js' %}"></script>
		<script src="{% static 'js/jquery.zoom.min.js' %}"></script>
		<script src="{% static 'js/main.js' %}"></script>
     <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script type="text/javascript" src="{% static 'js/cart.js' %}"></script>
	</body>
</html>

ecommerce/store/templates/store/productdetail.html
{% extends 'store/main.html' %}
{% load static %}
{% block content %}

       <div class="section">
			<!-- container -->
			<div class="container">
				<!-- row -->
				<div class="row">
					<!-- Product main img -->
					<div class="col-md-5 col-md-push-2">
						<div id="product-main-img">
							<div class="product-preview">
								<img src="{{product.imageURL}}" alt="">
							</div>
						</div>
					</div>
					<!-- /Product main img -->

					<!-- Product thumb imgs -->
					<div class="col-md-2  col-md-pull-5">
						<div id="product-imgs">
							<div class="product-preview">
								<img src="{{product.imageURL}}" alt="">
							</div>


						</div>
					</div>
					<!-- /Product thumb imgs -->

					<!-- Product details lấy-->
					<div class="col-md-5">
						<div class="product-details">
							<h2 class="product-name">{{product.name}}</h2>

							<div>
								<h3 class="product-price">${{product.price|floatformat:2}}</h3>

							</div>
							<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>


					<!-- /Product details -->

					<!-- Product tab lấy-->

								<!-- /tab3  -->

							<!-- /product tab content  -->
						</div>
					</div>
					<!-- /product tab -->
				</div>
				<!-- /row -->
			</div>
			<!-- /container -->
		</div>

{% endblock content %}

ecommerce/store/templates/store/store.html
{% extends 'store/main.html' %}
{% load static %}
{% block content %}

<div class="container" style="margin-top:50px">
     <div class="row">
		 {% for product in products %}
		<div class="col-lg-3">
			<div class="product">
				<div class="product-img">
					<img class="thumbnail" src="{{product.imageURL}}" alt="">
					<div class="product-label">
						<span class="new">NEW</span>
					</div>
				</div>
				<div class="product-body ">
					<p class="product-category">{{product.category}}</p>
					<h3 class="product-name"><a href="#">{{product.name}}</a></h3>
					<h4 class="product-price">{{product.price}} VNĐ</h4>

				</div>
				<div class="add-to-cart">
					<button data-product={{product.id}} data-action="add" class="add-to-cart-btn update-cart">thêm vào giỏ hàng</button>
				</div>
                <div id="slick-nav-1" class="products-slick-nav"></div>
			</div>
		</div>
{% endfor %}
	</div>
</div>
{% endblock content %}